declare namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_SUPABASE_URL?: string
    NEXT_PUBLIC_SUPABASE_ANON_KEY?: string
    NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY?: string
    SUPABASE_SERVICE_ROLE_KEY?: string
    SUPABASE_SECRET_KEY?: string
    NEXT_PUBLIC_SITE_URL?: string
    TWILIO_ACCOUNT_SID?: string
    TWILIO_AUTH_TOKEN?: string
    TWILIO_PHONE_NUMBER?: string
    TWILIO_WHATSAPP_FROM?: string
    TWILIO_SMS_FROM?: string
    TWILIO_FROM?: string
    WHATSAPP_CLOUD_TOKEN?: string
    WHATSAPP_CLOUD_PHONE_NUMBER_ID?: string
    CRON_SECRET?: string
    NEXT_PUBLIC_FIREBASE_API_KEY?: string
    NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN?: string
    NEXT_PUBLIC_FIREBASE_PROJECT_ID?: string
    NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET?: string
    NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID?: string
    NEXT_PUBLIC_FIREBASE_SENDER_ID?: string
    NEXT_PUBLIC_FIREBASE_APP_ID?: string
    NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID?: string
    NEXT_PUBLIC_FIREBASE_VAPID_KEY?: string
    NEXT_PUBLIC_FIREBASE_MESSAGING_VAPID_KEY?: string
    NEXT_PUBLIC_FIREBASE_WEB_PUSH_CERTIFICATE?: string
    FIREBASE_SERVICE_ACCOUNT?: string
    RESEND_API_KEY?: string
    RESEND_FROM?: string
    RESEND_AUTH_FROM?: string
    AUTH_OTP_PEPPER?: string
    SUPPORT_NOTIFY_EMAIL?: string
  }
}
