import type { LibraryExercise } from "@/lib/exercises/types"

function video(youtubeId: string): Pick<LibraryExercise, "youtubeId" | "videoUrl"> {
  return {
    youtubeId,
    videoUrl: `https://www.youtube.com/watch?v=${youtubeId}`,
  }
}

export const LIBRARY_EXERCISES: LibraryExercise[] = [
  {
    id: "chin-tuck",
    title: "Retracție cervicală (Chin Tuck)",
    description:
      "Adu bărbia ușor înapoi, ca și cum ai face un bărbie dublu controlat. Menține privirea orizontală. Activează flexorii profunzi, fără a împinge capul în jos.",
    region: "cervical",
    subcategory: "mobility-retraction",
    difficulty: "usor",
    equipment: "none",
    position: "sitting",
    sets: 3,
    reps: 10,
    durationSeconds: 75,
    ...video("2Moei_PG2Ds"),
  },
  {
    id: "thoracic-extension-chair",
    title: "Extensie toracală pe spătar",
    description:
      "Așază mâinile la ceafă, sprijină mijlocul toracelui pe spătar și deschide cutia toracică. Mișcarea vine din torace, nu din cervicală.",
    region: "cervical",
    subcategory: "mobility-retraction",
    difficulty: "mediu",
    equipment: "none",
    position: "sitting",
    sets: 3,
    reps: 8,
    durationSeconds: 90,
    ...video("4C-j_i7ebHM"),
  },
  {
    id: "scapular-setting",
    title: "Setare scapulară izometrică",
    description:
      "Adu omoplații ușor în jos și înăuntru, ca și cum i-ai pune în buzunarele din spate. Ține 5 secunde fără a ridica umerii.",
    region: "cervical",
    subcategory: "tone-posture",
    difficulty: "usor",
    equipment: "none",
    position: "sitting",
    sets: 3,
    reps: 12,
    durationSeconds: 80,
    ...video("KWVchSPBbks"),
  },
  {
    id: "band-row-posture",
    title: "Ramat cu bandă — postură",
    description:
      "Trage banda spre coaste, coatele pe lângă corp. Expiră la tracțiune. Controlează întoarcerea; nu lăsa umerii să urce.",
    region: "cervical",
    subcategory: "tone-posture",
    difficulty: "mediu",
    equipment: "bands",
    position: "standing",
    sets: 3,
    reps: 12,
    durationSeconds: 110,
    ...video("GZbfZ33Sdcs"),
  },
  {
    id: "upper-trap-stretch",
    title: "Stretch trapez superior",
    description:
      "Așază o mână sub șold, înclină capul opus și adaugă o presiune ușoară. Respiră în zona tensionată 20–30 de secunde.",
    region: "cervical",
    subcategory: "stretch-relax",
    difficulty: "usor",
    equipment: "none",
    position: "sitting",
    sets: 2,
    reps: 4,
    durationSeconds: 95,
    ...video("lO8hF0mD2Dc"),
  },
  {
    id: "foam-thoracic-roll",
    title: "Rulare toracală pe rulou",
    description:
      "Sprijină toracele pe rulou, genunchii flexați. Rulează lent pe segmentul T4–T10. Evită cervicala și lombarul jos.",
    region: "cervical",
    subcategory: "stretch-relax",
    difficulty: "mediu",
    equipment: "roller",
    position: "lying",
    sets: 2,
    reps: 8,
    durationSeconds: 120,
    ...video("5j21Pgf5i2g"),
  },
  {
    id: "dead-bug",
    title: "Dead Bug — control core",
    description:
      "Culcat pe spate, brațe și genunchi la 90°. Extinde opus braț-picior fără a pierde contactul lombarului cu solul. Mișcare lentă.",
    region: "lumbar",
    subcategory: "core-control",
    difficulty: "mediu",
    equipment: "none",
    position: "lying",
    sets: 3,
    reps: 8,
    durationSeconds: 130,
    ...video("4XLQpRI_X-8"),
  },
  {
    id: "bird-dog",
    title: "Bird Dog",
    description:
      "Din patrupedie, întinde brațul și piciorul opus. Menține bazinul stabil, fără a roti trunchiul. Ține 2–3 secunde.",
    region: "lumbar",
    subcategory: "core-control",
    difficulty: "mediu",
    equipment: "none",
    position: "lying",
    sets: 3,
    reps: 8,
    durationSeconds: 115,
    ...video("4Prc1UfqF6I"),
  },
  {
    id: "pelvic-tilt",
    title: "Înclinare pelvină posterioră",
    description:
      "Culcat, genunchii flexați. Aplatizează lombarul pe saltea prin bascularea bazinului. Ține 3 secunde, apoi revino.",
    region: "lumbar",
    subcategory: "lumbopelvic-mob",
    difficulty: "usor",
    equipment: "none",
    position: "lying",
    sets: 3,
    reps: 12,
    durationSeconds: 70,
    ...video("I7VplM0c3_I"),
  },
  {
    id: "cat-camel",
    title: "Cat–Camel (flexie–extensie)",
    description:
      "Din patrupedie, alternează rotunjirea și deschiderea coloanei. Mișcare fluidă, fără forțare la capete de amplitudine.",
    region: "lumbar",
    subcategory: "lumbopelvic-mob",
    difficulty: "usor",
    equipment: "none",
    position: "lying",
    sets: 2,
    reps: 10,
    durationSeconds: 85,
    ...video("kqnuaT7YA8I"),
  },
  {
    id: "knee-to-chest",
    title: "Genunchi la piept bilateral",
    description:
      "Adu ambele genunchi spre piept și ține ușor. Permite lombarului să se alungească. Respiră profund 20–30 de secunde.",
    region: "lumbar",
    subcategory: "decompression",
    difficulty: "usor",
    equipment: "none",
    position: "lying",
    sets: 2,
    reps: 6,
    durationSeconds: 90,
    ...video("8e8NkYkZgks"),
  },
  {
    id: "child-pose-lat",
    title: "Poziția copilului cu elongare",
    description:
      "Așază-te pe călcâie, brațele înainte, fruntea pe saltea. Lasă trunchiul să se lungească. Variantă: mâinile spre o parte pentru latissimus.",
    region: "lumbar",
    subcategory: "decompression",
    difficulty: "usor",
    equipment: "none",
    position: "lying",
    sets: 2,
    reps: 4,
    durationSeconds: 100,
    ...video("qPL2z8p0j9Y"),
  },
  {
    id: "er-band-side",
    title: "Rotație externă cu bandă (coafă)",
    description:
      "Cotul lipit de trunchi, la 90°. Rotește antebrațul în afară împotriva benzii. Nu deschide cotul de corp.",
    region: "upper",
    subcategory: "rotator-cuff",
    difficulty: "mediu",
    equipment: "bands",
    position: "standing",
    sets: 3,
    reps: 12,
    durationSeconds: 100,
    ...video("K7-z2sjyV5I"),
  },
  {
    id: "ir-band-side",
    title: "Rotație internă cu bandă",
    description:
      "Ancorează banda lateral. Cotul la 90°, trage palma spre abdomen. Controlează revenirea — eccentrica contează.",
    region: "upper",
    subcategory: "rotator-cuff",
    difficulty: "mediu",
    equipment: "bands",
    position: "standing",
    sets: 3,
    reps: 12,
    durationSeconds: 95,
    ...video("2L2lnxIcNmo"),
  },
  {
    id: "codman-pendulum",
    title: "Pendul Codman",
    description:
      "Lasă brațul să atârne relaxat. Mișcarea vine din balansul trunchiului, nu din umăr. Cercuri mici, fără durere.",
    region: "upper",
    subcategory: "scapulo-humeral",
    difficulty: "usor",
    equipment: "none",
    position: "standing",
    sets: 3,
    reps: 12,
    durationSeconds: 80,
    ...video("xpQM250vj3E"),
  },
  {
    id: "wall-slides",
    title: "Alunecări pe perete",
    description:
      "Spatele și antebrațele pe perete. Ridică brațele lent, fără a desprinde coatele sau a urca umerii.",
    region: "upper",
    subcategory: "scapulo-humeral",
    difficulty: "mediu",
    equipment: "none",
    position: "standing",
    sets: 3,
    reps: 10,
    durationSeconds: 90,
    ...video("KM36zdNUzZk"),
  },
  {
    id: "wrist-extensor-stretch",
    title: "Stretch extensori de pumn",
    description:
      "Cot întins, palma în jos. Cu cealaltă mână flectează pumnul. Ține 20–30 de secunde. Util în epicondilita laterală.",
    region: "upper",
    subcategory: "wrist-forearm",
    difficulty: "usor",
    equipment: "none",
    position: "sitting",
    sets: 2,
    reps: 4,
    durationSeconds: 70,
    ...video("v2vhhp-W0sY"),
  },
  {
    id: "wrist-eccentric-dumbbell",
    title: "Extensie de pumn excentrică",
    description:
      "Antebraț pe masă, pumnul în afară. Ridică gantera cu cealaltă mână, coboară lent 4 secunde. Protocol tip Tyler.",
    region: "upper",
    subcategory: "wrist-forearm",
    difficulty: "avansat",
    equipment: "dumbbells",
    position: "sitting",
    sets: 3,
    reps: 15,
    durationSeconds: 140,
    ...video("rva5YaWqfbs"),
  },
  {
    id: "tke-band",
    title: "Extensie terminală de genunchi (TKE)",
    description:
      "Bandă deasupra genunchiului, pas înapoi. Extinde genunchiul împotriva benzii până la aliniere, fără hiperextensie dureroasă.",
    region: "lower",
    subcategory: "knee-stability",
    difficulty: "mediu",
    equipment: "bands",
    position: "standing",
    sets: 3,
    reps: 12,
    durationSeconds: 95,
    ...video("POpqNc7BgBU"),
  },
  {
    id: "mini-squat",
    title: "Mini-genuflexiune controlată",
    description:
      "Genunchii pe direcția degetelor, greutatea pe călcâie. Coboară 30–45°, fără valgus. Urcă apăsând în podea.",
    region: "lower",
    subcategory: "knee-stability",
    difficulty: "usor",
    equipment: "none",
    position: "standing",
    sets: 3,
    reps: 10,
    durationSeconds: 85,
    ...video("aclHkVaku9U"),
  },
  {
    id: "clamshell",
    title: "Clamshell — mediu fesier",
    description:
      "Decubit lateral, genunchii flexați. Deschide genunchiul de sus fără a roti bazinul înapoi. Ține 1–2 secunde.",
    region: "lower",
    subcategory: "hip-mobility",
    difficulty: "usor",
    equipment: "none",
    position: "lying",
    sets: 3,
    reps: 12,
    durationSeconds: 90,
    ...video("SaORzJY4cSM"),
  },
  {
    id: "glute-bridge",
    title: "Punte fesieri",
    description:
      "Culcat, picioarele la lățimea bazinului. Ridică bazinul până la linie umăr–șold–genunchi. Evită hiperlordozarea.",
    region: "lower",
    subcategory: "hip-mobility",
    difficulty: "usor",
    equipment: "none",
    position: "lying",
    sets: 3,
    reps: 12,
    durationSeconds: 80,
    ...video("zp3RkBfa1zE"),
  },
  {
    id: "bosu-single-leg",
    title: "Sprijin unipodal pe BOSU",
    description:
      "Stai pe un picior pe BOSU, genunchi ușor flexat. Ține 20–30 de secunde. Privirea înainte, bazinul la nivel.",
    region: "lower",
    subcategory: "ankle-proprio",
    difficulty: "avansat",
    equipment: "ball",
    position: "standing",
    sets: 3,
    reps: 4,
    durationSeconds: 120,
    ...video("k2TKdWrVqwM"),
  },
  {
    id: "ankle-alphabet",
    title: "Alfabetul gleznei",
    description:
      "Șezând, piciorul în aer. Desenează literele cu vârful degetelor, mișcare din gleznă, nu din genunchi.",
    region: "lower",
    subcategory: "ankle-proprio",
    difficulty: "usor",
    equipment: "none",
    position: "sitting",
    sets: 2,
    reps: 2,
    durationSeconds: 100,
    ...video("J3jNl7eR0-E"),
  },
  {
    id: "tandem-stance",
    title: "Sprijin tandem",
    description:
      "Un picior în fața celuilalt, călcâi la degete. Ține 20–30 de secunde. Progresează cu ochii închiși dacă e stabil.",
    region: "functional",
    subcategory: "advanced-balance",
    difficulty: "mediu",
    equipment: "none",
    position: "standing",
    sets: 3,
    reps: 4,
    durationSeconds: 90,
    ...video("7h_9Ert0qY8"),
  },
  {
    id: "star-excursion",
    title: "Star excursion (atingeri)",
    description:
      "Pe un picior, atinge cu celălalt 5 direcții pe podea fără a pierde controlul bazinului. Revino central după fiecare atingere.",
    region: "functional",
    subcategory: "advanced-balance",
    difficulty: "avansat",
    equipment: "none",
    position: "standing",
    sets: 2,
    reps: 5,
    durationSeconds: 150,
    ...video("oCKCqC6d9n4"),
  },
  {
    id: "sit-to-stand",
    title: "Ridicare de pe scaun (sit-to-stand)",
    description:
      "Picioarele la lățimea bazinului. Apleacă trunchiul, ridică-te fără impuls din mâini dacă e posibil. Controlează așezarea.",
    region: "functional",
    subcategory: "gait-transfers",
    difficulty: "usor",
    equipment: "none",
    position: "sitting",
    sets: 3,
    reps: 8,
    durationSeconds: 85,
    ...video("2NPP5CbOJ-4"),
  },
  {
    id: "step-up",
    title: "Urcare pe treaptă",
    description:
      "Urcă cu piciorul de lucru, extinde șoldul și genunchiul. Coboară controlat. Evită împingerea din piciorul de jos.",
    region: "functional",
    subcategory: "gait-transfers",
    difficulty: "mediu",
    equipment: "none",
    position: "standing",
    sets: 3,
    reps: 10,
    durationSeconds: 110,
    ...video("dQqApCGd5Zc"),
  },
  {
    id: "diaphragmatic-breath",
    title: "Respirație diafragmatică",
    description:
      "O mână pe abdomen, una pe piept. Inspiră pe nas — abdomenul se ridică, pieptul rămâne liniștit. Expiră lung pe gură.",
    region: "functional",
    subcategory: "breathing",
    difficulty: "usor",
    equipment: "none",
    position: "lying",
    sets: 2,
    reps: 8,
    durationSeconds: 120,
    ...video("8VwufJqF5iQ"),
  },
  {
    id: "ball-reset-breath",
    title: "Relaxare pe minge — reset respirator",
    description:
      "Așază-te pe minge, picioarele stabile. Leagănă ușor bazinul și sincronizează respirația. Umerii coborâți, maxilarul relaxat.",
    region: "functional",
    subcategory: "breathing",
    difficulty: "usor",
    equipment: "ball",
    position: "sitting",
    sets: 2,
    reps: 6,
    durationSeconds: 140,
    ...video("1Q4h6pY9x2k"),
  },
]
